import React, { createContext, useContext, useState } from 'react';

const translations = {
    vi: {
        appTitle: "진일 라벨",
        pro: "Pro",
        searchPlaceholder: "Tìm kiếm...",
        logout: "Đăng xuất",
        login: "Đăng nhập",
        loginGoogle: "Google",
        progressTitle: "Tiến độ công việc",
        tasksCompleted: "công việc đã hoàn thành",
        addTaskPlaceholder: "Thêm công việc mới...",
        priorityHigh: "Quan trọng",
        priorityNormal: "Bình thường",
        priorityLow: "Không quan trọng",
        filterAll: "Tất cả",
        filterActive: "Đang làm",
        filterCompleted: "Hoàn thành",
        noTasks: "Chưa có công việc nào!",
        noMatchingTasks: "Không tìm thấy công việc nào phù hợp.",
        today: "Hôm nay",
        jan: "Tháng 1", feb: "Tháng 2", mar: "Tháng 3", apr: "Tháng 4", may: "Tháng 5", jun: "Tháng 6",
        jul: "Tháng 7", aug: "Tháng 8", sep: "Tháng 9", oct: "Tháng 10", nov: "Tháng 11", dec: "Tháng 12",
        sun: "CN", mon: "T2", tue: "T3", wed: "T4", thu: "T5", fri: "T6", sat: "T7",
        calendarLegend: "Chú thích lịch",
        hasActiveTasks: "Có việc chưa làm",
        hasCompletedTasks: "Đã hoàn thành hết",
        selectedDate: "Ngày đang chọn",
        loading: "Đang tải dữ liệu...",
        tasksForDate: "Công việc ngày",
        allTasksTitle: "Tất cả công việc",
        viewAllDates: "Xem tất cả các ngày",
        autoSave: "Lưu tự động",
        koreanNews: "Tin tức Hàn Quốc",
        loadingNews: "Đang tải tin tức...",
        holidayRed: "Ngày lễ (Đỏ)",
        waybillNumber: "Mã vận đơn",
        delivery: "택배",
        newUpload: "Ảnh mới đã tải lên",
        newUploadText: "Một ảnh bưu kiện mới đã được đăng ký.",
        loginFailPerm: "Đăng nhập thất bại: Hãy chắc chắn bạn đã cấp quyền cho tiện ích.",
        loginFailGeneric: "Đăng nhập thất bại: ",
        emailPassRequired: "Vui lòng nhập email và mật khẩu",
        invalidEmailPass: "Email hoặc mật khẩu không đúng",
        marketWidgetTitle: "Thị trường Hàn Quốc",
        goldPrice: "Vàng (1g)",
        searchStocks: "Tìm mã cổ phiếu...",
        noResults: "Không tìm thấy",
        updatedAt: "Cập nhật lúc",
        deliveryWidgetTitle: "택배",
        noDeliveries: "Chưa có bưu kiện nào",
        addDelivery: "Thêm",
        cancel: "Huỷ",
        orderCodePlaceholder: "Nhập mã đơn hàng",
        takePhoto: "Chụp ảnh",
        upload: "Tải lên",
        uploading: "Đang tải...",
        successUpload: "Tải lên thành công!",
        successUploadText: "Hình ảnh đã được lưu thành công.",
        exportExcel: "Xuất Excel",
        delete: "Xóa",
        time: "Thời gian",
        barcode: "Mã vạch",
        uploadedBy: "Người đăng",
        timeSuffix: "còn lại",
        timePassed: "Đã quá giờ",
        timeHours: "giờ",
        timeMinutes: "phút",
        timeSeconds: "giây",
        copy: "Sao chép",
        save: "Lưu",
        print: "In",
        printA4: "In bản A4",
        copiedToast: "Đã sao chép",
        closeEsc: "Đóng (Esc)",
        saveCtrlS: "Lưu (Ctrl+S)",
        noImage: "Không có ảnh",
        invoice: "Số hóa đơn",
        loadingShort: "Đang tải...",
        clientAddressBook: "Sổ địa chỉ khách hàng",
        inventoryManagement: "Quản lý kho",
        category: "Phân loại",
        productName: "Tên sản phẩm",
        productCode: "Mã sản phẩm",
        initialStock: "Tồn đầu kỳ",
        stockIn: "Nhập kho",
        stockOut: "Xuất kho",
        currentStock: "Tồn hiện tại",
        client: "Khách hàng",
        inPrice: "Đơn giá nhập",
        outPrice: "Đơn giá xuất",
        companyName: "Tên công ty",
        representative: "Người đại diện",
        businessNo: "Mã số thuế",
        address: "Địa chỉ",
        homepage: "Trang web",
        phone: "Số điện thoại",
        fax: "Số Fax",
        mobile: "Di động",
        contactName: "Tên người liên hệ",
        noData: "Không có dữ liệu",
        search: "Tìm kiếm",
        addNew: "Thêm mới",
        confirmDeleteTitle: "Bạn có chắc chắn?",
        confirmDeleteText: "Hành động này không thể hoàn tác!",
        yes: "Đồng ý",
        no: "Hủy",
        number: "STT",
        success: "Thành công",
        error: "Lỗi",
        labelPrinting: "In barcode",
        labelPaperSize: "Kích cỡ giấy",
        labelWidth: "Chiều rộng",
        labelHeight: "Chiều cao",
        labelFontSize: "Cỡ chữ",
        labelCopies: "Số bản",
        labelOption: "Tùy chọn",
        labelPrice: "Giá",
        labelPrint: "In nhãn",
        labelAddRow: "Thêm hàng",
        labelPreview: "Xem trước",
        labelPreviewEmpty: "Nhập dữ liệu...",
        labelMoreItems: "mục nữa",
        labelImportInventory: "Từ kho",
        labelSelectProduct: "Chọn sản phẩm",
        labelTip: "Mẹo",
        labelTipText: "Chọn kích cỡ giấy phù hợp với máy in. Thiết lập kích cỡ giấy tùy chỉnh trong cài đặt máy in trước khi in."
    },
    ko: {
        appTitle: "진일 라벨",
        pro: "프로",
        searchPlaceholder: "검색...",
        logout: "로그아웃",
        login: "로그인",
        loginGoogle: "구글",
        progressTitle: "작업 진행률",
        tasksCompleted: "완료된 작업",
        addTaskPlaceholder: "새 작업 추가...",
        priorityHigh: "중요",
        priorityNormal: "보통",
        priorityLow: "중요하지 않음",
        filterAll: "모두",
        filterActive: "진행 중",
        filterCompleted: "완료됨",
        noTasks: "작업이 없습니다!",
        noMatchingTasks: "일치하는 작업을 찾을 수 없습니다.",
        today: "오늘",
        jan: "1월", feb: "2월", mar: "3월", apr: "4월", may: "5월", jun: "6월",
        jul: "7월", aug: "8월", sep: "9월", oct: "10월", nov: "11월", dec: "12월",
        sun: "일", mon: "월", tue: "화", wed: "수", thu: "목", fri: "금", sat: "토",
        calendarLegend: "일정 안내",
        hasActiveTasks: "미완료 작업 있음",
        hasCompletedTasks: "모두 완료됨",
        selectedDate: "선택한 날짜",
        loading: "데이터 불러오는 중...",
        tasksForDate: "작업 날짜",
        allTasksTitle: "모든 작업",
        viewAllDates: "모든 날짜 보기",
        autoSave: "자동 저장",
        koreanNews: "한국 뉴스",
        loadingNews: "뉴스 불러오는 중...",
        holidayRed: "공휴일 (빨간날)",
        waybillNumber: "송장번호",
        delivery: "택배",
        newUpload: "새로운 사진 업로드",
        newUploadText: "새로운 택배 사진이 등록되었습니다.",
        loginFailPerm: "로그인 실패: 확장 프로그램 권한을 확인하세요.",
        loginFailGeneric: "로그인 실패: ",
        emailPassRequired: "이메일과 비밀번호를 입력하세요.",
        invalidEmailPass: "이메일 또는 비밀번호가 올바르지 않습니다.",
        marketWidgetTitle: "한국 금융 시장",
        goldPrice: "금 (1g)",
        searchStocks: "종목 검색...",
        noResults: "결과 없음",
        updatedAt: "업데이트 시간:",
        deliveryWidgetTitle: "택배",
        noDeliveries: "등록된 택배가 없습니다",
        addDelivery: "추가",
        cancel: "취소",
        orderCodePlaceholder: "주문번호 입력",
        takePhoto: "사진 찍기",
        upload: "등록하기",
        uploading: "업로드 중...",
        successUpload: "업로드 성공!",
        successUploadText: "이미지가 성공적으로 저장되었습니다.",
        exportExcel: "엑셀 다운로드",
        delete: "삭제",
        time: "시간",
        barcode: "송장번호",
        uploadedBy: "등록자",
        timeSuffix: "남음",
        timePassed: "시간 지남",
        timeHours: "시간",
        timeMinutes: "분",
        timeSeconds: "초",
        copy: "복사",
        save: "저장",
        print: "인쇄",
        printA4: "A4 인쇄",
        copiedToast: "복사되었습니다",
        closeEsc: "닫기 (Esc)",
        saveCtrlS: "저장 (Ctrl+S)",
        noImage: "이미지 없음",
        invoice: "송장",
        loadingShort: "불러오는 중...",
        clientAddressBook: "거래처 주소록",
        inventoryManagement: "재고 관리",
        category: "구분",
        productName: "상품명",
        productCode: "상품코드",
        initialStock: "기초 재고",
        stockIn: "입고",
        stockOut: "출고",
        currentStock: "현 재고",
        client: "거래처",
        inPrice: "입고단가",
        outPrice: "출고단가",
        companyName: "업체명",
        representative: "대표자",
        businessNo: "사업자번호",
        address: "주소",
        homepage: "홈페이지",
        phone: "전화번호",
        fax: "팩스번호",
        mobile: "휴대폰",
        contactName: "담당자명",
        noData: "데이터가 없습니다",
        search: "검색",
        addNew: "새로 추가",
        confirmDeleteTitle: "정말 삭제하시겠습니까?",
        confirmDeleteText: "이 작업은 되돌릴 수 없습니다!",
        yes: "예",
        no: "아니오",
        number: "번호",
        success: "성공",
        error: "오류",
        labelPrinting: "바코드 인쇄",
        labelPaperSize: "용지 크기",
        labelWidth: "너비",
        labelHeight: "높이",
        labelFontSize: "글자 크기",
        labelCopies: "매수",
        labelOption: "옵션",
        labelPrice: "가격",
        labelPrint: "인쇄",
        labelAddRow: "행 추가",
        labelPreview: "미리 보기",
        labelPreviewEmpty: "데이터 입력...",
        labelMoreItems: "개 더",
        labelImportInventory: "재고에서 가져오기",
        labelSelectProduct: "상품 선택",
        labelTip: "팁",
        labelTipText: "프린터에 맞는 용지 크기를 선택하세요. 인쇄 전 프린터 설정에서 사용자 정의 용지 크기를 설정하세요."
    }
};

/* eslint-disable react-refresh/only-export-components */
const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState('ko');

    const toggleLanguage = () => {
        setLang(prev => (prev === 'vi' ? 'ko' : 'vi'));
    };

    const t = (key) => translations[lang][key] || key;

    return (
        <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
